# Generated by Django 3.2.8 on 2021-10-11 18:53

import custom.blocks.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("wagtailimages", "0023_add_choose_permissions"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogDetailsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("blog_title", models.CharField(max_length=50)),
                (
                    "content",
                    wagtail.core.fields.StreamField(
                        [("full_richtext", custom.blocks.blocks.RichtextBlock())],
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "blog_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Detail",
                "verbose_name_plural": "Blog(s) Detail",
            },
            bases=("wagtailcore.page",),
        ),
    ]
