# Generated by Django 3.2.8 on 2021-10-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogdetailspage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogdetailspage",
            name="blog_title",
        ),
    ]
