# Generated by Django 3.2.8 on 2021-10-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_category_categoryorderable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
            },
        ),
    ]
