# Generated by Django 3.2.8 on 2021-10-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_rename_blogdetailspage_blogdetails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogdetails",
            old_name="blog_image",
            new_name="blog_background_image",
        ),
    ]
