# Generated by Django 3.2.8 on 2021-10-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteNameSettings",
        ),
    ]
