# Generated by Django 3.2.8 on 2021-10-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("site_settings", "0004_sitenamesettings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SiteNameSettings",
            new_name="SiteOwnerShipSettings",
        ),
    ]
