# Generated by Django 3.2.8 on 2021-10-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0008_remove_siteownershipsettings_site_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteownershipsettings",
            name="site_name",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
