# Generated by Django 3.2.8 on 2021-10-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0009_siteownershipsettings_site_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteOwnerShipSettings",
        ),
    ]
